all:
		clear
		lex lexica.l
		yacc -d sintatica.y
		g++ -o glf y.tab.c -lfl
		./glf < exemplo.soft

exemplo1:
			./glf < exemplo1.soft > teste.cpp
			g++ teste.cpp
			./a.out

exemplo2:
			./glf < exemplo2.soft > teste.cpp
			g++ teste.cpp
			./a.out

exemplo3:
			./glf < exemplo3.soft > teste.cpp
			g++ teste.cpp
			./a.out

exemplo4:
			./glf < exemplo4.soft > teste.cpp
			g++ teste.cpp
			./a.out

exemplo5:
			./glf < exemplo5.soft > teste.cpp
			g++ teste.cpp
			./a.out

exemplo6:
			./glf < exemplo6.soft > teste.cpp
			g++ teste.cpp
			./a.out

exemplo7:
			./glf < exemplo7.soft > teste.cpp
			g++ teste.cpp
			./a.out

exemplo8:
			./glf < exemplo8.soft > teste.cpp
			g++ teste.cpp
			./a.out